### ISSUE TITLE
Spawn in wall

### ISSUE THREAD

**Issue by pearsons** [ceruleanlabs/Chicago-Game-Jam-2013#1]
I've spawned in walls at the beginning of levels a few times (maybe held down as level was loading?). Also, if you stop burning in a gate it keeps you stuck there. Cool stuff

**Comment by pearsons** [comment]
As in the game is cool stuff

**Comment by bergren2** [comment]
Ah yes, we'll have to take a look at both those bugs. A short term fix would be to add a Reset button since those bugs can still occur even after we made some attempts to fix them.

**Comment by bergren2** [comment]
Reset button already added and haven't been able to reproduce. Closing.
